# Build Ubuntu image with base functionality.

FROM ubuntu:focal AS ubuntu-base
RUN apt-get update && apt-get install -y git
RUN apt-get install -y libpython3-dev
ENV DEBIAN_FRONTEND noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"] 
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo ubuntu
RUN echo 'ubuntu:ubuntu' | chpasswd
USER ubuntu
WORKDIR /home/ubuntu

# Build image with Python and SSHD.
FROM ubuntu-base AS ubuntu-with-sshd
USER root

# Install required tools.
RUN apt-get -qq update \
    && apt-get -qq --no-install-recommends install vim-tiny=2:8.1.* \
    && apt-get -qq --no-install-recommends install sudo=1.8.* \
    && apt-get -qq --no-install-recommends install python3-pip=20.0.* \
    && apt-get -qq --no-install-recommends install openssh-server=1:8.* \
    && apt-get -qq clean    \
    && rm -rf /var/lib/apt/lists/*

# Configure sudo.
RUN ex +"%s/^%sudo.*$/%sudo ALL=(ALL:ALL) NOPASSWD:ALL/g" -scwq! /etc/sudoers

# Generate and configure user keys.
USER ubuntu
RUN cd /home/ubuntu

RUN mkdir /home/ubuntu/.ssh
RUN sudo mkdir /public_key_server


USER ubuntu
RUN pip3 install tensorflow==2.2.0
RUN pip3 install scikit-learn
RUN pip3 install dill

RUN git clone https://github.com/cc-hpc-itwm/Fed-DART.git /home/ubuntu/Fed-DART
RUN cd /home/ubuntu/Fed-DART && pip3 install .
RUN cd /home/ubuntu/Fed-DART/dart && tar -xf dart_x86_64.tar.gz

WORKDIR /home/ubuntu/Fed-DART/dart/dart/bin/ 
USER ubuntu
ADD entrypoint_client.sh /entrypoint_client.sh
RUN rm /home/ubuntu/Fed-DART/dart/dart/worker/worker.json
ADD worker.json /home/ubuntu/Fed-DART/dart/dart/worker/worker.json
USER root
RUN chmod +x /entrypoint_client.sh
USER  ubuntu

ENTRYPOINT ["/entrypoint_client.sh"]