.common_build_job:
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ${FEDDART_CI_BUILD_DIR}

  script:
    - echo FEDDART_BUILD_TYPE=${FEDDART_BUILD_TYPE}

.release_job:
  variables:
    FEDDART_BUILD_TYPE: Release

.debug_job:
  variables:
    FEDDART_BUILD_TYPE: Debug
