.common_build_job:
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ${CI_PROJECT_DIR}
  tags:
    - feddart
  script:
    - echo FEDDART_BUILD_TYPE=${FEDDART_BUILD_TYPE}

.release_job:
  variables:
    FEDDART_BUILD_TYPE: Release

.debug_job:
  variables:
    FEDDART_BUILD_TYPE: Debug


.common_after_script:
  after_script:
    - echo FEDDART_BUILD_TYPE=${FEDDART_BUILD_TYPE}
