.common_build_job:
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ${CI_PROJECT_DIR}
  tags:
    - feddart
  script:
    - cd ${CI_PROJECT_DIR}
    - ./install.sh

.conda_build_job:
  tags:
    - feddart
  before_script:
    - cd ${CI_PROJECT_DIR}
    - ./prepare_conda.sh
    - conda activate fed_dart_env
    - pip install -U pytest

.release_job:
  variables:
    FEDDART_BUILD_TYPE: Release

.debug_job:
  variables:
    FEDDART_BUILD_TYPE: Debug


.common_after_script:
  after_script:
    - echo FEDDART_BUILD_TYPE=${FEDDART_BUILD_TYPE}

###########Build Jobs############
default_build:
  extends:
    - .conda_build_job
    - .common_build_job
  stage: build
