.feddart_devicelist_common:
  tags:
    - feddart
  script:
    - cd ${FEDDART_CI_DIR}
    - pwd

###########Build Jobs############
default_build:
  extends:
    - .feddart_devicelist_common
  stage:
    - build
  script:
    - pwd