.feddart_devicelist_common:
  tags:
    - feddart
  script:
    - pwd
    - cd ${FEDDART_CI_DIR}
    - pwd

.feddart_devicelist_run_tests:
  extends:
    - .feddart_devicelist_common
  stage: unit_tests_python
  script:
    - pwd

###########Build Jobs############
default_build:
  extends:
    - .common_build_job
  stage: build
  
default_tests:
  extends:
    - .feddart_devicelist_run_tests
  needs:
    - job: default_build
  
