.feddart_devicelist_common:
  tags:
    - feddart
  script:
    - pwd
    - cd ${FEDDART_CI_DIR}
    - pwd

.feddart_devicelist_run_tests:
  extends:
    - .feddart_devicelist_common
  stage: unit_tests_python
  script:
    - echo 'Running unit tests...'

.feddart_devicelist_run_integration_tests:
  extends:
    - .feddart_devicelist_common
  stage: integration_tests
  script:
    - echo 'Running unit tests...'

###########Build Jobs############ 
default_tests:
  extends:
    - .feddart_devicelist_run_tests
    - .feddart_devicelist_run_integration_tests
  needs:
    - job: default_build
  
