.feddart_devicelist_common:
  tags:
    - feddart
  script:
    - pwd

.feddart_devicelist_run_tests:
  extends:
    - .feddart_devicelist_common
  stage: unit_tests_python
  script:
    - echo 'Running unit tests...'
    - cd ${FEDDART_CI_DIR}/tests/unittests
    - conda activate fed_dart_env
    - ./run-all.sh

.feddart_devicelist_run_integration_tests:
  extends:
    - .feddart_devicelist_common
  stage: integration_tests
  script:
    - echo 'Running integration tests...'

###########Build Jobs############ 
default_tests:
  extends:
    - .feddart_devicelist_run_tests
    #- .feddart_devicelist_run_integration_tests
  needs:
    - job: default_build
  
