stages:
  - build
  - unit_tests_python
  - integration_tests
  - integration_tests_nightly

tags: 
  - feddart

variables:
  GIT_STRATEGY: fetch
  FEDDART_CI_DIR: ${CI_PROJECT_DIR}/meta/ci
  FEDDART_CI_INSTALL_DIR: ${CI_PROJECT_DIR}/install
  FEDDART_CI_BUILD_DIR: ${CI_PROJECT_DIR}/build
  FEDDART_CI_LD_LIBRARY_PATH: ${CI_PROJECT_DIR}/build
  RUNNER_HOME: /home/gitlab-runner

include: 
  - local: meta/ci/config/common.yml
